name: entmix-tabred
channels:
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
  - pytorch
  - nodefaults
dependencies:
  - python=3.11
  - category_encoders=2.6.3
  - joblib=1.4.0
  - loguru=0.7.2
  - numpy=1.26.4
  - pandas=2.2.1
  - plotnine=0.13.4
  - polars=0.20.19
  - pyarrow=15.0.2
  - kaggle=1.6.11
  - pytorch::pytorch=2.2
  - pytorch::pytorch-cuda=12.1
  - scikit-learn=1.4.1.post1
  - scipy=1.13.0
  - tensorboard=2.16.2
  - tqdm=4.66.2
  - tomli=2.0.1
  - tomli-w=1.0
  - pytest=8.2.1
  - pip
  - pip:
      - delu==0.0.23
      - rtdl_num_embeddings==0.0.9
      - rtdl_revisiting_models==0.0.2
